// PlayStation 1 Model Export
// Generated by PS1 Exporter for Blender 4.0
// Model: moon
// Coordinate System: Z-up (PS1)

#ifndef MOON_H
#define MOON_H

#include <sys/types.h>
#include <libgte.h>

#define MOON_VERTICES_COUNT 4
#define MOON_UVS_COUNT 4
#define MOON_FACES_COUNT 1
#define MOON_TRI_COUNT 0
#define MOON_QUAD_COUNT 1
#define MOON_PS1_SCALE 3072

// Vertices (fixed-point, scaled by 3072)
SVECTOR moon_vertices[MOON_VERTICES_COUNT] = {
    { -1807, -8412, 9703 },
    { 1807, -8412, 9703 },
    { -1807, -12028, 9703 },
    { 1807, -12028, 9703 },
};

// Normals (for lighting calculations)
SVECTOR moon_normals[MOON_VERTICES_COUNT] = {
    { 0, 0, -4095 },
    { 0, 0, -4095 },
    { 0, 0, -4095 },
    { 0, 0, -4095 },
};

// Texture references
#define MOON_TEXTURE_COUNT 1
#define MOON_TEXTURE_0_NAME "moontexture.png"
#define MOON_TEXTURE_MOONTEXTURE 0

// UV Coordinates
SVECTOR moon_uvs[MOON_UVS_COUNT] = {
    { 25, 25, 0 },
    { 231, 25, 0 },
    { 25, 231, 0 },
    { 231, 231, 0 },
};

// Faces
int moon_tri_faces[1][3] = { {0, 0, 0} };
int moon_tri_uvs[1][3] = { {0, 0, 0} };

int moon_quad_faces[1][4] = {
    { 2, 3, 0, 1 },
};

int moon_quad_uvs[1][4] = {
    { 0, 1, 2, 3 },
};

unsigned char moon_material_flags[MOON_FACES_COUNT] = {
    0b00100011,  // unlit, textured, flat, cutout
};

// Vertex Colors
#define MOON_VERTEX_COLORS_COUNT 1
CVECTOR moon_vertex_colors[MOON_VERTEX_COLORS_COUNT] = {
    { 128, 128, 128, 0 }  // Default gray
};

#endif
