// PlayStation 1 Model Export
// Generated by PS1 Exporter for Blender 4.0
// Model: star
// Coordinate System: Z-up (PS1)

#ifndef STAR_H
#define STAR_H

#include <sys/types.h>
#include <libgte.h>

#define STAR_VERTICES_COUNT 12
#define STAR_UVS_COUNT 60
#define STAR_FACES_COUNT 20
#define STAR_TRI_COUNT 20
#define STAR_QUAD_COUNT 0
#define STAR_PS1_SCALE 3072

// Vertices (fixed-point, scaled by 3072)
SVECTOR star_vertices[STAR_VERTICES_COUNT] = {
    { -7686, -6007, 3242 },
    { -7270, -4331, 3242 },
    { -8119, -4786, 3242 },
    { -8119, -6852, 3242 },
    { -6721, -6003, 3242 },
    { -8119, -5576, 3511 },
    { -8119, -5576, 2973 },
    { -7473, -5222, 3242 },
    { -8552, -6007, 3242 },
    { -8968, -4331, 3242 },
    { -9517, -6003, 3242 },
    { -8765, -5222, 3242 },
};

// Normals (for lighting calculations)
SVECTOR star_normals[STAR_VERTICES_COUNT] = {
    { 1672, -3739, 0 },
    { 2428, 3298, 0 },
    { 0, 4096, 0 },
    { 0, -4096, 0 },
    { 3822, -1472, 0 },
    { 0, -122, 4094 },
    { 0, -122, -4094 },
    { 4044, 649, 0 },
    { -1672, -3739, 0 },
    { -2428, 3298, 0 },
    { -3822, -1472, 0 },
    { -4044, 649, 0 },
};

// Texture references
#define STAR_TEXTURE_COUNT 1
#define STAR_TEXTURE_0_NAME "gold"
#define STAR_TEXTURE_GOLD 0

// UV Coordinates
SVECTOR star_uvs[STAR_UVS_COUNT] = {
    { 64, 66, 0 },
    { 64, 8, 0 },
    { 44, 46, 0 },
    { 29, 27, 0 },
    { 54, 19, 0 },
    { 37, 19, 0 },
    { 64, 66, 0 },
    { 35, 82, 0 },
    { 26, 122, 0 },
    { 1, 46, 0 },
    { 64, 66, 0 },
    { 44, 46, 0 },
    { 26, 122, 0 },
    { 64, 102, 0 },
    { 64, 66, 0 },
    { 37, 19, 0 },
    { 29, 4, 0 },
    { 29, 27, 0 },
    { 29, 41, 0 },
    { 44, 49, 0 },
    { 29, 27, 0 },
    { 44, 49, 0 },
    { 41, 33, 0 },
    { 29, 27, 0 },
    { 64, 66, 0 },
    { 1, 46, 0 },
    { 35, 82, 0 },
    { 41, 33, 0 },
    { 54, 19, 0 },
    { 29, 27, 0 },
    { 64, 66, 0 },
    { 84, 46, 0 },
    { 64, 8, 0 },
    { 29, 27, 0 },
    { 21, 19, 0 },
    { 4, 19, 0 },
    { 64, 66, 0 },
    { 102, 122, 0 },
    { 93, 82, 0 },
    { 127, 46, 0 },
    { 84, 46, 0 },
    { 64, 66, 0 },
    { 102, 122, 0 },
    { 64, 66, 0 },
    { 64, 102, 0 },
    { 21, 19, 0 },
    { 29, 27, 0 },
    { 29, 4, 0 },
    { 29, 41, 0 },
    { 29, 27, 0 },
    { 14, 49, 0 },
    { 14, 49, 0 },
    { 29, 27, 0 },
    { 17, 33, 0 },
    { 64, 66, 0 },
    { 93, 82, 0 },
    { 127, 46, 0 },
    { 17, 33, 0 },
    { 29, 27, 0 },
    { 4, 19, 0 },
};

// Faces
int star_tri_faces[20][3] = {
    { 6, 3, 0 },
    { 5, 4, 0 },
    { 6, 7, 1 },
    { 4, 6, 0 },
    { 1, 2, 6 },
    { 0, 3, 5 },
    { 2, 1, 5 },
    { 1, 7, 5 },
    { 6, 4, 7 },
    { 7, 4, 5 },
    { 6, 8, 3 },
    { 5, 8, 10 },
    { 6, 9, 11 },
    { 10, 8, 6 },
    { 9, 6, 2 },
    { 8, 5, 3 },
    { 2, 5, 9 },
    { 9, 5, 11 },
    { 6, 11, 10 },
    { 11, 5, 10 },
};

int star_tri_uvs[20][3] = {
    { 0, 1, 2 },
    { 3, 4, 5 },
    { 6, 7, 8 },
    { 9, 10, 11 },
    { 12, 13, 14 },
    { 15, 16, 17 },
    { 18, 19, 20 },
    { 21, 22, 23 },
    { 24, 25, 26 },
    { 27, 28, 29 },
    { 30, 31, 32 },
    { 33, 34, 35 },
    { 36, 37, 38 },
    { 39, 40, 41 },
    { 42, 43, 44 },
    { 45, 46, 47 },
    { 48, 49, 50 },
    { 51, 52, 53 },
    { 54, 55, 56 },
    { 57, 58, 59 },
};

int star_quad_faces[1][4] = { {0, 0, 0, 0} };
int star_quad_uvs[1][4] = { {0, 0, 0, 0} };

unsigned char star_material_flags[STAR_FACES_COUNT] = {
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
    0b01000110,  // lit, textured, smooth, specular(0.15)
};

// Specular values (0-255, where 255 = maximum specular)
unsigned char star_specular[STAR_FACES_COUNT] = {
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
    37,  // 0.15
};

// Vertex Colors
#define STAR_VERTEX_COLORS_COUNT 1
CVECTOR star_vertex_colors[STAR_VERTEX_COLORS_COUNT] = {
    { 128, 128, 128, 0 }  // Default gray
};

#endif
